version: "3.8"

services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://nestjs-app:4000/v1
      - SECRET_API_KEY=my-secret-api-key
      - NEXTAUTH_URL=http://localhost:3000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true
