import type { Metadata } from 'next'
import '../globals.css'
import '@fontsource/inter'
import BaseLayout from '../components/BaseLayout'
import { ToastProvider } from '../providers/toast-provider'

export const metadata: Metadata = {
  title: 'KAI',
  description: 'Generated by create next app'
}

export default async function DashboardLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <BaseLayout>
      {children}
    </BaseLayout>
  )
}
